import os

DB = os.getenv("KUMO_DB", "KUMO_ADMIN")
SCHEMA = os.getenv("KUMO_SCHEMA", "WORKFLOW_MANAGER")

T_WORKFLOWS = f"{DB}.{SCHEMA}.WORKFLOWS"
T_TASKS = f"{DB}.{SCHEMA}.WORKFLOW_TASKS"
T_HISTORY = f"{DB}.{SCHEMA}.WORKFLOW_HISTORY"
T_QUEUE = f"{DB}.{SCHEMA}.WORKFLOW_RUN_QUEUE"
T_LOGS = f"{DB}.{SCHEMA}.WORKFLOW_RUN_LOGS"
T_NOTIFICATIONS = f"{DB}.{SCHEMA}.WORKFLOW_NOTIFICATIONS"

DEFAULT_TASK_WAREHOUSE = os.getenv("KUMO_TASK_WAREHOUSE", "KUMO_ELT_GEN_1")
PROGRESS_TABLE = os.getenv("KUMO_PROGRESS_TABLE", "KUMO_TST.META.EXECUTION_PROGRESS")
RUN_LOG_TABLE = os.getenv("KUMO_RUN_LOG_TABLE", "KUMO_TST.META.RUN_LOG")
REFRESH_SECONDS = int(os.getenv("KUMO_REFRESH_SECONDS", "5"))
USE_MOCK = os.getenv("KUMO_USE_MOCK", "false").lower() in ("1", "true", "yes", "y")

SNOWFLAKE_ACCOUNT = os.getenv("SNOWFLAKE_ACCOUNT", "")
SNOWFLAKE_USER = os.getenv("SNOWFLAKE_USER", "")
SNOWFLAKE_PASSWORD = os.getenv("SNOWFLAKE_PASSWORD", "")
SNOWFLAKE_ROLE = os.getenv("SNOWFLAKE_ROLE", "")
SNOWFLAKE_WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE", "")
SNOWFLAKE_DATABASE = os.getenv("SNOWFLAKE_DATABASE", DB)
SNOWFLAKE_SCHEMA = os.getenv("SNOWFLAKE_SCHEMA", SCHEMA)

# Manual run behavior:
# procedure = call SP_WORKFLOW_REQUEST_RUN first (same path as scheduled task), then fallback to queue insert if needed.
# queue = only insert WORKFLOW_HISTORY + WORKFLOW_RUN_QUEUE rows.
KUMO_MANUAL_RUN_MODE = os.getenv("KUMO_MANUAL_RUN_MODE", "procedure").strip().lower()
