from datetime import datetime, timezone, timedelta

now = datetime.now(timezone.utc)

MOCK_MONITOR = {
    "source": "mock",
    "engine": {"status": "RUNNING", "task": "TASK_WF_MASTER_DISPATCHER"},
    "summary": {"total": 5, "success": 2, "failed": 1, "running": 1, "queued": 1},
    "workflows": [
        {
            "workflowId": "wf-001",
            "workflowGroup": "Finance",
            "workflowName": "Load Ledger",
            "workflowType": "DBT",
            "workflowEnabled": True,
            "taskEnabled": True,
            "lastRunId": "run-001",
            "lastStatus": "RUNNING",
            "lastStartTime": (now - timedelta(minutes=6, seconds=14)).isoformat(),
            "lastEndTime": None,
            "lastDurationSeconds": None,
            "scheduleCron": "*/15 * * * *",
            "scheduleTimezone": "Europe/Stockholm",
            "nextRunTime": (now + timedelta(minutes=8)).isoformat(),
            "indent": 0,
            "progress": {"total": 18, "done": 11, "running": 2, "failed": 0, "percent": 61},
        },
        {
            "workflowId": "wf-002",
            "workflowGroup": "Finance",
            "workflowName": "Validate Ledger",
            "workflowType": "SQL",
            "workflowEnabled": True,
            "taskEnabled": True,
            "lastRunId": "run-002",
            "lastStatus": "QUEUED",
            "lastStartTime": None,
            "lastEndTime": None,
            "lastDurationSeconds": None,
            "scheduleCron": "*/15 * * * *",
            "scheduleTimezone": "Europe/Stockholm",
            "nextRunTime": (now + timedelta(minutes=9)).isoformat(),
            "indent": 1,
            "progress": None,
        },
        {
            "workflowId": "wf-003",
            "workflowGroup": "Sales",
            "workflowName": "Customer Mart",
            "workflowType": "DBT",
            "workflowEnabled": True,
            "taskEnabled": True,
            "lastRunId": "run-003",
            "lastStatus": "SUCCESS",
            "lastStartTime": (now - timedelta(hours=1, minutes=2)).isoformat(),
            "lastEndTime": (now - timedelta(minutes=47)).isoformat(),
            "lastDurationSeconds": 900,
            "scheduleCron": "0 * * * *",
            "scheduleTimezone": "Europe/Stockholm",
            "nextRunTime": (now + timedelta(minutes=13)).isoformat(),
            "indent": 0,
            "progress": {"total": 14, "done": 14, "running": 0, "failed": 0, "percent": 100},
        },
        {
            "workflowId": "wf-004",
            "workflowGroup": "Risk",
            "workflowName": "Risk Exposure Daily",
            "workflowType": "SQL",
            "workflowEnabled": False,
            "taskEnabled": False,
            "lastRunId": "run-004",
            "lastStatus": "FAILED",
            "lastStartTime": (now - timedelta(hours=3)).isoformat(),
            "lastEndTime": (now - timedelta(hours=2, minutes=52)).isoformat(),
            "lastDurationSeconds": 480,
            "scheduleCron": "0 6 * * *",
            "scheduleTimezone": "Europe/Stockholm",
            "nextRunTime": None,
            "indent": 0,
            "progress": {"total": 8, "done": 6, "running": 0, "failed": 2, "percent": 75},
        },
        {
            "workflowId": "wf-005",
            "workflowGroup": "Operations",
            "workflowName": "Operational Metrics",
            "workflowType": "DBT",
            "workflowEnabled": True,
            "taskEnabled": True,
            "lastRunId": "run-005",
            "lastStatus": "SUCCESS",
            "lastStartTime": (now - timedelta(hours=4)).isoformat(),
            "lastEndTime": (now - timedelta(hours=3, minutes=55)).isoformat(),
            "lastDurationSeconds": 300,
            "scheduleCron": "*/30 * * * *",
            "scheduleTimezone": "Europe/Stockholm",
            "nextRunTime": (now + timedelta(minutes=22)).isoformat(),
            "indent": 0,
            "progress": {"total": 5, "done": 5, "running": 0, "failed": 0, "percent": 100},
        },
    ],
    "generatedAt": now.isoformat(),
    "error": None,
}

MOCK_HISTORY = [
    {"RUN_ID": "run-005", "WORKFLOW_ID": "wf-005", "STATUS": "SUCCESS", "START_TIME": (now - timedelta(hours=4)).isoformat(), "END_TIME": (now - timedelta(hours=3, minutes=55)).isoformat()},
    {"RUN_ID": "run-004", "WORKFLOW_ID": "wf-004", "STATUS": "FAILED", "START_TIME": (now - timedelta(hours=3)).isoformat(), "END_TIME": (now - timedelta(hours=2, minutes=52)).isoformat()},
]
