-- Extend the new KUMO_TST.MONITOR_APP model with the relationship features
-- proven in KUMO_ADMIN.SANDBOX. This migration only reads from SANDBOX.

ALTER TABLE KUMO_TST.MONITOR_APP.WORKFLOW
  ADD COLUMN IF NOT EXISTS EXTERNAL_TRIGGERS VARIANT;

UPDATE KUMO_TST.MONITOR_APP.WORKFLOW
SET EXTERNAL_TRIGGERS = ARRAY_CONSTRUCT_COMPACT(
  IFF(IS_SCHEDULE_ENABLED, 'SCHEDULE', NULL),
  IFF(ALLOW_EXTERNAL_TRIGGER, 'EXTERNAL', NULL)
)
WHERE EXTERNAL_TRIGGERS IS NULL;

ALTER TABLE KUMO_TST.MONITOR_APP.JOB
  ADD COLUMN IF NOT EXISTS ON_SUCCESS_COMMAND_LINE VARCHAR;

ALTER TABLE KUMO_TST.MONITOR_APP.JOB
  ADD COLUMN IF NOT EXISTS ON_WARNING_COMMAND_LINE VARCHAR;

ALTER TABLE KUMO_TST.MONITOR_APP.JOB
  ADD COLUMN IF NOT EXISTS ON_ERROR_COMMAND_LINE VARCHAR;

ALTER TABLE KUMO_TST.MONITOR_APP.WORKFLOW_JOB
  ADD COLUMN IF NOT EXISTS PARENT_JOB_ID VARCHAR(36);

ALTER TABLE KUMO_TST.MONITOR_APP.WORKFLOW_JOB
  ADD COLUMN IF NOT EXISTS MIN_STATUS_LEVEL VARCHAR(50) NOT NULL DEFAULT 'SUCCESS';

ALTER TABLE KUMO_TST.MONITOR_APP.WORKFLOW_JOB
  ADD COLUMN IF NOT EXISTS DEPENDENCY_TYPE VARCHAR(50) NOT NULL DEFAULT 'SEQUENCE';

ALTER TABLE KUMO_TST.MONITOR_APP.WORKFLOW_JOB SET
  COMMENT = 'Workflow membership, execution order and parent/child job dependencies';

CREATE TABLE IF NOT EXISTS KUMO_TST.MONITOR_APP.WORKFLOW_DEPENDENCY (
  WORKFLOW_DEPENDENCY_ID  VARCHAR(36)   NOT NULL DEFAULT UUID_STRING(),
  PARENT_WORKFLOW_ID      VARCHAR(36)   NOT NULL,
  CHILD_WORKFLOW_ID       VARCHAR(36)   NOT NULL,
  MIN_STATUS_LEVEL        VARCHAR(50)   NOT NULL DEFAULT 'SUCCESS',
  DEPENDENCY_TYPE         VARCHAR(50)   NOT NULL DEFAULT 'TRIGGER',
  IS_ENABLED              BOOLEAN       NOT NULL DEFAULT TRUE,
  CREATED_AT              TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY              VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),
  UPDATED_AT              TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY              VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),
  CONSTRAINT PK_MONITOR_WORKFLOW_DEPENDENCY PRIMARY KEY (WORKFLOW_DEPENDENCY_ID),
  CONSTRAINT FK_MONITOR_WF_DEP_PARENT FOREIGN KEY (PARENT_WORKFLOW_ID)
    REFERENCES KUMO_TST.MONITOR_APP.WORKFLOW (WORKFLOW_ID),
  CONSTRAINT FK_MONITOR_WF_DEP_CHILD FOREIGN KEY (CHILD_WORKFLOW_ID)
    REFERENCES KUMO_TST.MONITOR_APP.WORKFLOW (WORKFLOW_ID),
  CONSTRAINT UQ_MONITOR_WORKFLOW_DEPENDENCY UNIQUE (PARENT_WORKFLOW_ID, CHILD_WORKFLOW_ID)
)
COMMENT = 'Status-aware relationships between workflows';

-- Copy prototype workflows using canonical IDs and column names.
MERGE INTO KUMO_TST.MONITOR_APP.WORKFLOW T
USING (
  SELECT
    WF_ID::VARCHAR AS WORKFLOW_ID,
    WF_NAME AS WORKFLOW_NAME,
    TRY_PARSE_JSON(REPLACE(EXTERNAL_TRIGGERS, '''', '"')) AS EXTERNAL_TRIGGERS,
    EXTERNAL_TRIGGERS ILIKE '%SCHEDULE%' AS IS_SCHEDULE_ENABLED,
    EXTERNAL_TRIGGERS ILIKE '%EXTERNAL%' AS ALLOW_EXTERNAL_TRIGGER
  FROM KUMO_ADMIN.SANDBOX.WORKFLOW_ATTRIBUTE
) S
ON T.WORKFLOW_ID = S.WORKFLOW_ID
WHEN NOT MATCHED THEN INSERT (
  WORKFLOW_ID, WORKFLOW_NAME, WORKFLOW_GROUP, DESCRIPTION,
  EXTERNAL_TRIGGERS, IS_SCHEDULE_ENABLED, ALLOW_MANUAL_TRIGGER,
  ALLOW_EXTERNAL_TRIGGER, IS_ENABLED
) VALUES (
  S.WORKFLOW_ID, S.WORKFLOW_NAME, 'SANDBOX PROTOTYPE',
  'Migrated from KUMO_ADMIN.SANDBOX.WORKFLOW_ATTRIBUTE',
  S.EXTERNAL_TRIGGERS, S.IS_SCHEDULE_ENABLED, TRUE,
  S.ALLOW_EXTERNAL_TRIGGER, TRUE
);

-- Copy prototype jobs and normalize the misspelled success callback column.
MERGE INTO KUMO_TST.MONITOR_APP.JOB T
USING KUMO_ADMIN.SANDBOX.JOB_ATTRIBUTE S
ON T.JOB_ID = S.JOB_ID::VARCHAR
WHEN NOT MATCHED THEN INSERT (
  JOB_ID, JOB_NAME, DESCRIPTION, JOB_TYPE, COMMAND_LINE,
  ON_SUCCESS_COMMAND_LINE, ON_WARNING_COMMAND_LINE, ON_ERROR_COMMAND_LINE,
  IS_ENABLED
) VALUES (
  S.JOB_ID::VARCHAR, S.JOB_NAME,
  'Migrated from KUMO_ADMIN.SANDBOX.JOB_ATTRIBUTE', 'COMMAND', S.COMMAND_LINE,
  S.ON_SUCESS_COMMAND_LINE, S.ON_WARNING_COMMAND_LINE, S.ON_ERROR_COMMAND_LINE,
  TRUE
);

-- Copy workflow membership and internal job dependencies. Canonical columns
-- replace JOB_ID_CHILD and the misspelled DEPENDECY_TYPE from the prototype.
MERGE INTO KUMO_TST.MONITOR_APP.WORKFLOW_JOB T
USING (
  SELECT
    D.WF_ID::VARCHAR AS WORKFLOW_ID,
    D.JOB_ID_CHILD::VARCHAR AS JOB_ID,
    D.JOB_ID_PARENT::VARCHAR AS PARENT_JOB_ID,
    ROW_NUMBER() OVER (
      PARTITION BY D.WF_ID
      ORDER BY IFF(D.JOB_ID_PARENT IS NULL, 0, 1), J.JOB_NAME
    ) AS JOB_SEQUENCE,
    COALESCE(D.MIN_STATUS_LEVEL, 'SUCCESS') AS MIN_STATUS_LEVEL,
    COALESCE(D.DEPENDECY_TYPE, 'SEQUENCE') AS DEPENDENCY_TYPE
  FROM KUMO_ADMIN.SANDBOX.WORKFLOW_DEFINITION D
  JOIN KUMO_ADMIN.SANDBOX.JOB_ATTRIBUTE J
    ON J.JOB_ID = D.JOB_ID_CHILD
) S
ON T.WORKFLOW_ID = S.WORKFLOW_ID AND T.JOB_ID = S.JOB_ID
WHEN MATCHED THEN UPDATE SET
  T.PARENT_JOB_ID = S.PARENT_JOB_ID,
  T.JOB_SEQUENCE = S.JOB_SEQUENCE,
  T.MIN_STATUS_LEVEL = S.MIN_STATUS_LEVEL,
  T.DEPENDENCY_TYPE = S.DEPENDENCY_TYPE,
  T.UPDATED_AT = CURRENT_TIMESTAMP(),
  T.UPDATED_BY = CURRENT_USER()
WHEN NOT MATCHED THEN INSERT (
  WORKFLOW_ID, JOB_ID, PARENT_JOB_ID, JOB_SEQUENCE,
  MIN_STATUS_LEVEL, DEPENDENCY_TYPE, IS_ENABLED
) VALUES (
  S.WORKFLOW_ID, S.JOB_ID, S.PARENT_JOB_ID, S.JOB_SEQUENCE,
  S.MIN_STATUS_LEVEL, S.DEPENDENCY_TYPE, TRUE
);

-- Copy cross-workflow trigger/blocker relationships with canonical names.
MERGE INTO KUMO_TST.MONITOR_APP.WORKFLOW_DEPENDENCY T
USING (
  SELECT
    WF_DEP_ID::VARCHAR AS WORKFLOW_DEPENDENCY_ID,
    WF_ID_PARENT::VARCHAR AS PARENT_WORKFLOW_ID,
    WF_ID_CHILD::VARCHAR AS CHILD_WORKFLOW_ID,
    COALESCE(MIN_STATUS_LEVEL, 'SUCCESS') AS MIN_STATUS_LEVEL,
    COALESCE(DEPENDECY_TYPE, 'TRIGGER') AS DEPENDENCY_TYPE
  FROM KUMO_ADMIN.SANDBOX.WORKFLOW_DEPENDENCY
) S
ON T.WORKFLOW_DEPENDENCY_ID = S.WORKFLOW_DEPENDENCY_ID
WHEN NOT MATCHED THEN INSERT (
  WORKFLOW_DEPENDENCY_ID, PARENT_WORKFLOW_ID, CHILD_WORKFLOW_ID,
  MIN_STATUS_LEVEL, DEPENDENCY_TYPE, IS_ENABLED
) VALUES (
  S.WORKFLOW_DEPENDENCY_ID, S.PARENT_WORKFLOW_ID, S.CHILD_WORKFLOW_ID,
  S.MIN_STATUS_LEVEL, S.DEPENDENCY_TYPE, TRUE
);
