-- Add a canonical data-platform layer to every reusable job.

ALTER TABLE KUMO_TST.MONITOR_APP.JOB
  ADD COLUMN IF NOT EXISTS JOB_LAYER VARCHAR(50) NOT NULL DEFAULT 'GENERAL';

UPDATE KUMO_TST.MONITOR_APP.JOB
SET
  JOB_LAYER = CASE
    WHEN COALESCE(MIGRATED_FROM_WORKFLOW_STEP, DBT_COMMAND, JOB_NAME) ILIKE '%/RAW/%'
      OR JOB_NAME ILIKE '%READY TO LOAD%'
      OR JOB_NAME ILIKE '%RAW%'
      OR SQL_COMMAND ILIKE '%RAW_LIM%'
      THEN 'RAW'
    WHEN COALESCE(MIGRATED_FROM_WORKFLOW_STEP, DBT_COMMAND, JOB_NAME) ILIKE '%/SDL/%'
      OR REGEXP_LIKE(UPPER(JOB_NAME), '^SDL_.*')
      OR JOB_NAME ILIKE '% SDL'
      THEN 'SDL'
    WHEN COALESCE(MIGRATED_FROM_WORKFLOW_STEP, DBT_COMMAND, JOB_NAME) ILIKE '%/EDV/%'
      OR REGEXP_LIKE(UPPER(JOB_NAME), '^EDV_.*')
      OR JOB_NAME ILIKE '% EDV'
      THEN 'EDV'
    WHEN COALESCE(MIGRATED_FROM_WORKFLOW_STEP, DBT_COMMAND, JOB_NAME) ILIKE '%/BDL/%'
      OR REGEXP_LIKE(UPPER(JOB_NAME), '^BDL_.*')
      OR JOB_NAME ILIKE '% BDL'
      THEN 'BDL'
    ELSE 'GENERAL'
  END,
  UPDATED_AT = CURRENT_TIMESTAMP(),
  UPDATED_BY = CURRENT_USER();
