-- New workflow engine track. This migration is intentionally additive and does
-- not modify the current KUMO_ADMIN.WORKFLOW_MANAGER implementation.

CREATE SCHEMA IF NOT EXISTS KUMO_TST.MONITOR_APP
  COMMENT = 'Application logic and runtime objects for the next-generation KUMO workflow engine';

CREATE SCHEMA IF NOT EXISTS KUMO_TST.MONITOR_META
  COMMENT = 'Configuration, audit and execution metadata for the next-generation KUMO workflow engine';

CREATE TABLE IF NOT EXISTS KUMO_TST.MONITOR_APP.WORKFLOW (
  WORKFLOW_ID              VARCHAR(36)   NOT NULL DEFAULT UUID_STRING(),
  WORKFLOW_NAME            VARCHAR(255)  NOT NULL,
  WORKFLOW_GROUP           VARCHAR(255),
  DESCRIPTION              VARCHAR,
  EXTERNAL_TRIGGERS        VARIANT,

  -- The workflow remains a Snowflake task, but only orchestrates its jobs.
  TASK_NAME                VARCHAR(255),
  WAREHOUSE_NAME           VARCHAR(255),
  SCHEDULE                 VARCHAR(500),
  SCHEDULE_TIMEZONE        VARCHAR(100),
  IS_SCHEDULE_ENABLED      BOOLEAN       NOT NULL DEFAULT FALSE,
  ALLOW_MANUAL_TRIGGER     BOOLEAN       NOT NULL DEFAULT TRUE,
  ALLOW_EXTERNAL_TRIGGER   BOOLEAN       NOT NULL DEFAULT FALSE,
  IS_ENABLED               BOOLEAN       NOT NULL DEFAULT TRUE,
  MIGRATED_FROM_WORKFLOW_ID VARCHAR(255),

  CREATED_AT               TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY               VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),
  UPDATED_AT               TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY               VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),

  CONSTRAINT PK_MONITOR_WORKFLOW PRIMARY KEY (WORKFLOW_ID),
  CONSTRAINT UQ_MONITOR_WORKFLOW_NAME UNIQUE (WORKFLOW_NAME)
)
COMMENT = 'Workflow containers and trigger configuration; executable logic belongs to JOB';

CREATE TABLE IF NOT EXISTS KUMO_TST.MONITOR_APP.JOB (
  JOB_ID                    VARCHAR(36)   NOT NULL DEFAULT UUID_STRING(),
  JOB_NAME                  VARCHAR(255)  NOT NULL,
  DESCRIPTION               VARCHAR,
  JOB_TYPE                  VARCHAR(50)   NOT NULL,
  JOB_LAYER                 VARCHAR(50)   NOT NULL DEFAULT 'GENERAL',

  -- A job is the executable unit. During migration these values come from the
  -- equivalent fields on the current WORKFLOWS table.
  TASK_NAME                 VARCHAR(255),
  COMMAND_LINE              VARCHAR,
  SQL_COMMAND               VARCHAR,
  DBT_COMMAND               VARCHAR,
  DBT_TARGET                VARCHAR(255),
  DBT_WORKSPACE             VARCHAR(500),
  DBT_PROJECT_FQN           VARCHAR(500),
  ON_SUCCESS_COMMAND_LINE   VARCHAR,
  ON_WARNING_COMMAND_LINE   VARCHAR,
  ON_ERROR_COMMAND_LINE     VARCHAR,
  TIMEOUT_SECONDS           NUMBER(9, 0),
  IS_ENABLED                BOOLEAN       NOT NULL DEFAULT TRUE,

  -- Retains lineage while old workflows are migrated piece by piece.
  MIGRATED_FROM_WORKFLOW_ID VARCHAR(255),
  MIGRATED_FROM_WORKFLOW_STEP VARCHAR(500),

  CREATED_AT                TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY                VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),
  UPDATED_AT                TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY                VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),

  CONSTRAINT PK_MONITOR_JOB PRIMARY KEY (JOB_ID),
  CONSTRAINT UQ_MONITOR_JOB_NAME UNIQUE (JOB_NAME)
)
COMMENT = 'Reusable executable units that can be assigned to one or more workflows';

CREATE TABLE IF NOT EXISTS KUMO_TST.MONITOR_APP.WORKFLOW_JOB (
  WORKFLOW_JOB_ID          VARCHAR(36)   NOT NULL DEFAULT UUID_STRING(),
  WORKFLOW_ID              VARCHAR(36)   NOT NULL,
  JOB_ID                   VARCHAR(36)   NOT NULL,
  PARENT_JOB_ID            VARCHAR(36),
  JOB_SEQUENCE             NUMBER(9, 0)  NOT NULL,
  MIN_STATUS_LEVEL         VARCHAR(50)   NOT NULL DEFAULT 'SUCCESS',
  DEPENDENCY_TYPE          VARCHAR(50)   NOT NULL DEFAULT 'SEQUENCE',
  IS_ENABLED               BOOLEAN       NOT NULL DEFAULT TRUE,

  CREATED_AT               TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY               VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),
  UPDATED_AT               TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY               VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),

  CONSTRAINT PK_MONITOR_WORKFLOW_JOB PRIMARY KEY (WORKFLOW_JOB_ID),
  CONSTRAINT FK_MONITOR_WORKFLOW_JOB_WORKFLOW FOREIGN KEY (WORKFLOW_ID)
    REFERENCES KUMO_TST.MONITOR_APP.WORKFLOW (WORKFLOW_ID),
  CONSTRAINT FK_MONITOR_WORKFLOW_JOB_JOB FOREIGN KEY (JOB_ID)
    REFERENCES KUMO_TST.MONITOR_APP.JOB (JOB_ID),
  CONSTRAINT FK_MONITOR_WORKFLOW_JOB_PARENT FOREIGN KEY (PARENT_JOB_ID)
    REFERENCES KUMO_TST.MONITOR_APP.JOB (JOB_ID),
  CONSTRAINT UQ_MONITOR_WORKFLOW_JOB UNIQUE (WORKFLOW_ID, JOB_ID),
  CONSTRAINT UQ_MONITOR_WORKFLOW_JOB_SEQUENCE UNIQUE (WORKFLOW_ID, JOB_SEQUENCE)
)
COMMENT = 'Workflow membership, execution order and parent/child job dependencies';

CREATE TABLE IF NOT EXISTS KUMO_TST.MONITOR_APP.WORKFLOW_DEPENDENCY (
  WORKFLOW_DEPENDENCY_ID  VARCHAR(36)   NOT NULL DEFAULT UUID_STRING(),
  PARENT_WORKFLOW_ID      VARCHAR(36)   NOT NULL,
  CHILD_WORKFLOW_ID       VARCHAR(36)   NOT NULL,
  MIN_STATUS_LEVEL        VARCHAR(50)   NOT NULL DEFAULT 'SUCCESS',
  DEPENDENCY_TYPE         VARCHAR(50)   NOT NULL DEFAULT 'TRIGGER',
  IS_ENABLED              BOOLEAN       NOT NULL DEFAULT TRUE,

  CREATED_AT              TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY              VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),
  UPDATED_AT              TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY              VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),

  CONSTRAINT PK_MONITOR_WORKFLOW_DEPENDENCY PRIMARY KEY (WORKFLOW_DEPENDENCY_ID),
  CONSTRAINT FK_MONITOR_WF_DEP_PARENT FOREIGN KEY (PARENT_WORKFLOW_ID)
    REFERENCES KUMO_TST.MONITOR_APP.WORKFLOW (WORKFLOW_ID),
  CONSTRAINT FK_MONITOR_WF_DEP_CHILD FOREIGN KEY (CHILD_WORKFLOW_ID)
    REFERENCES KUMO_TST.MONITOR_APP.WORKFLOW (WORKFLOW_ID),
  CONSTRAINT UQ_MONITOR_WORKFLOW_DEPENDENCY UNIQUE (PARENT_WORKFLOW_ID, CHILD_WORKFLOW_ID)
)
COMMENT = 'Status-aware relationships between workflows';
