-- Migrate every current KUMO workflow into the next-generation model.
-- This is additive and idempotent: legacy workflows/tasks remain unchanged.
-- SQL workflows become one job. Each selector in a DBT command becomes its
-- own ordered job, so SDL and EDV can execute as distinct units.

ALTER TABLE KUMO_TST.MONITOR_APP.WORKFLOW
  ADD COLUMN IF NOT EXISTS MIGRATED_FROM_WORKFLOW_ID VARCHAR(255);

ALTER TABLE KUMO_TST.MONITOR_APP.JOB
  ADD COLUMN IF NOT EXISTS MIGRATED_FROM_WORKFLOW_STEP VARCHAR(500);

-- Link previously migrated rows, including LOAD RAW DAILY, to their source.
UPDATE KUMO_TST.MONITOR_APP.WORKFLOW T
SET MIGRATED_FROM_WORKFLOW_ID = S.WORKFLOW_ID
FROM KUMO_ADMIN.WORKFLOW_MANAGER.WORKFLOWS S
WHERE T.MIGRATED_FROM_WORKFLOW_ID IS NULL
  AND UPPER(T.WORKFLOW_NAME) = UPPER(S.WORKFLOW_NAME);

UPDATE KUMO_TST.MONITOR_APP.JOB
SET MIGRATED_FROM_WORKFLOW_STEP = IFF(JOB_TYPE = 'DBT', DBT_COMMAND, 'SQL')
WHERE MIGRATED_FROM_WORKFLOW_ID IS NOT NULL
  AND MIGRATED_FROM_WORKFLOW_STEP IS NULL;

-- Workflow containers retain their current group, audit and task schedule.
MERGE INTO KUMO_TST.MONITOR_APP.WORKFLOW T
USING (
  SELECT
    W.WORKFLOW_ID AS SOURCE_WORKFLOW_ID,
    W.WORKFLOW_NAME,
    W.WORKFLOW_GROUP,
    W.DESCRIPTION,
    WT.SCHEDULE_CRON AS SCHEDULE,
    COALESCE(WT.SCHEDULE_TIMEZONE, 'UTC') AS SCHEDULE_TIMEZONE,
    COALESCE(WT.IS_ENABLED, FALSE) AS IS_SCHEDULE_ENABLED,
    W.IS_ENABLED,
    ARRAY_CONSTRUCT_COMPACT(
      'EXTERNAL',
      IFF(COALESCE(WT.IS_ENABLED, FALSE), 'SCHEDULE', NULL)
    ) AS EXTERNAL_TRIGGERS,
    W.CREATED_AT,
    COALESCE(W.CREATED_BY, 'UNKNOWN') AS CREATED_BY,
    GREATEST_IGNORE_NULLS(W.UPDATED_AT, WT.UPDATED_AT) AS UPDATED_AT,
    COALESCE(W.UPDATED_BY, WT.UPDATED_BY, W.CREATED_BY, 'UNKNOWN') AS UPDATED_BY
  FROM KUMO_ADMIN.WORKFLOW_MANAGER.WORKFLOWS W
  LEFT JOIN KUMO_ADMIN.WORKFLOW_MANAGER.WORKFLOW_TASKS WT
    ON WT.WORKFLOW_ID = W.WORKFLOW_ID
) S
ON T.MIGRATED_FROM_WORKFLOW_ID = S.SOURCE_WORKFLOW_ID
WHEN MATCHED THEN UPDATE SET
  T.WORKFLOW_NAME = S.WORKFLOW_NAME,
  T.WORKFLOW_GROUP = S.WORKFLOW_GROUP,
  T.DESCRIPTION = S.DESCRIPTION,
  T.SCHEDULE = S.SCHEDULE,
  T.SCHEDULE_TIMEZONE = S.SCHEDULE_TIMEZONE,
  T.IS_SCHEDULE_ENABLED = S.IS_SCHEDULE_ENABLED,
  T.ALLOW_MANUAL_TRIGGER = TRUE,
  T.ALLOW_EXTERNAL_TRIGGER = TRUE,
  T.EXTERNAL_TRIGGERS = S.EXTERNAL_TRIGGERS,
  T.IS_ENABLED = S.IS_ENABLED,
  T.CREATED_AT = S.CREATED_AT,
  T.CREATED_BY = S.CREATED_BY,
  T.UPDATED_AT = S.UPDATED_AT,
  T.UPDATED_BY = S.UPDATED_BY
WHEN NOT MATCHED THEN INSERT (
  WORKFLOW_NAME, WORKFLOW_GROUP, DESCRIPTION,
  SCHEDULE, SCHEDULE_TIMEZONE, IS_SCHEDULE_ENABLED,
  ALLOW_MANUAL_TRIGGER, ALLOW_EXTERNAL_TRIGGER, EXTERNAL_TRIGGERS,
  IS_ENABLED, MIGRATED_FROM_WORKFLOW_ID,
  CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY
) VALUES (
  S.WORKFLOW_NAME, S.WORKFLOW_GROUP, S.DESCRIPTION,
  S.SCHEDULE, S.SCHEDULE_TIMEZONE, S.IS_SCHEDULE_ENABLED,
  TRUE, TRUE, S.EXTERNAL_TRIGGERS,
  S.IS_ENABLED, S.SOURCE_WORKFLOW_ID,
  S.CREATED_AT, S.CREATED_BY, S.UPDATED_AT, S.UPDATED_BY
);

-- One executable job for each legacy SQL workflow.
MERGE INTO KUMO_TST.MONITOR_APP.JOB T
USING (
  SELECT
    W.WORKFLOW_ID AS SOURCE_WORKFLOW_ID,
    W.WORKFLOW_NAME AS JOB_NAME,
    W.DESCRIPTION,
    IFF(
      W.WORKFLOW_NAME ILIKE '%READY TO LOAD%'
        OR W.WORKFLOW_NAME ILIKE '%RAW%'
        OR W.SQL_COMMAND ILIKE '%RAW_LIM%',
      'RAW', 'GENERAL'
    ) AS JOB_LAYER,
    W.SQL_COMMAND,
    W.IS_ENABLED,
    W.CREATED_AT,
    COALESCE(W.CREATED_BY, 'UNKNOWN') AS CREATED_BY,
    W.UPDATED_AT,
    COALESCE(W.UPDATED_BY, W.CREATED_BY, 'UNKNOWN') AS UPDATED_BY
  FROM KUMO_ADMIN.WORKFLOW_MANAGER.WORKFLOWS W
  WHERE UPPER(W.WORKFLOW_TYPE) = 'SQL'
) S
ON T.MIGRATED_FROM_WORKFLOW_ID = S.SOURCE_WORKFLOW_ID
AND T.MIGRATED_FROM_WORKFLOW_STEP = 'SQL'
WHEN MATCHED THEN UPDATE SET
  T.JOB_NAME = S.JOB_NAME,
  T.DESCRIPTION = S.DESCRIPTION,
  T.JOB_TYPE = 'SQL',
  T.JOB_LAYER = S.JOB_LAYER,
  T.SQL_COMMAND = S.SQL_COMMAND,
  T.DBT_COMMAND = NULL,
  T.IS_ENABLED = S.IS_ENABLED,
  T.CREATED_AT = S.CREATED_AT,
  T.CREATED_BY = S.CREATED_BY,
  T.UPDATED_AT = S.UPDATED_AT,
  T.UPDATED_BY = S.UPDATED_BY
WHEN NOT MATCHED THEN INSERT (
  JOB_NAME, DESCRIPTION, JOB_TYPE, JOB_LAYER, SQL_COMMAND, IS_ENABLED,
  MIGRATED_FROM_WORKFLOW_ID, MIGRATED_FROM_WORKFLOW_STEP,
  CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY
) VALUES (
  S.JOB_NAME, S.DESCRIPTION, 'SQL', S.JOB_LAYER, S.SQL_COMMAND, S.IS_ENABLED,
  S.SOURCE_WORKFLOW_ID, 'SQL',
  S.CREATED_AT, S.CREATED_BY, S.UPDATED_AT, S.UPDATED_BY
);

-- Split DBT commands after -s into one job per model selector.
MERGE INTO KUMO_TST.MONITOR_APP.JOB T
USING (
  SELECT
    W.WORKFLOW_ID AS SOURCE_WORKFLOW_ID,
    TRIM(F.VALUE::VARCHAR) AS MODEL_SELECTOR,
    CONCAT(
      COALESCE(NULLIF(W.WORKFLOW_GROUP, ''), W.WORKFLOW_NAME),
      ' ', UPPER(SPLIT_PART(TRIM(F.VALUE::VARCHAR), '/', -2))
    ) AS JOB_NAME,
    CONCAT('Migrated DBT selector ', TRIM(F.VALUE::VARCHAR), ' from ', W.WORKFLOW_NAME) AS DESCRIPTION,
    CONCAT('dbt build -s ', TRIM(F.VALUE::VARCHAR)) AS DBT_COMMAND,
    CASE
      WHEN TRIM(F.VALUE::VARCHAR) ILIKE '%/RAW/%' THEN 'RAW'
      WHEN TRIM(F.VALUE::VARCHAR) ILIKE '%/SDL/%' THEN 'SDL'
      WHEN TRIM(F.VALUE::VARCHAR) ILIKE '%/EDV/%' THEN 'EDV'
      WHEN TRIM(F.VALUE::VARCHAR) ILIKE '%/BDL/%' THEN 'BDL'
      ELSE 'GENERAL'
    END AS JOB_LAYER,
    W.DBT_TARGET,
    W.DBT_WORKSPACE,
    W.DBT_PROJECT_FQN,
    W.IS_ENABLED,
    W.CREATED_AT,
    COALESCE(W.CREATED_BY, 'UNKNOWN') AS CREATED_BY,
    W.UPDATED_AT,
    COALESCE(W.UPDATED_BY, W.CREATED_BY, 'UNKNOWN') AS UPDATED_BY
  FROM KUMO_ADMIN.WORKFLOW_MANAGER.WORKFLOWS W,
       LATERAL SPLIT_TO_TABLE(
         TRIM(SUBSTR(W.DBT_COMMAND, POSITION('-s' IN W.DBT_COMMAND) + 2)), ' '
       ) F
  WHERE UPPER(W.WORKFLOW_TYPE) = 'DBT'
    AND TRIM(F.VALUE::VARCHAR) <> ''
) S
ON T.MIGRATED_FROM_WORKFLOW_ID = S.SOURCE_WORKFLOW_ID
AND T.MIGRATED_FROM_WORKFLOW_STEP = S.MODEL_SELECTOR
WHEN MATCHED THEN UPDATE SET
  T.JOB_NAME = S.JOB_NAME,
  T.DESCRIPTION = S.DESCRIPTION,
  T.JOB_TYPE = 'DBT',
  T.JOB_LAYER = S.JOB_LAYER,
  T.SQL_COMMAND = NULL,
  T.DBT_COMMAND = S.DBT_COMMAND,
  T.DBT_TARGET = S.DBT_TARGET,
  T.DBT_WORKSPACE = S.DBT_WORKSPACE,
  T.DBT_PROJECT_FQN = S.DBT_PROJECT_FQN,
  T.IS_ENABLED = S.IS_ENABLED,
  T.CREATED_AT = S.CREATED_AT,
  T.CREATED_BY = S.CREATED_BY,
  T.UPDATED_AT = S.UPDATED_AT,
  T.UPDATED_BY = S.UPDATED_BY
WHEN NOT MATCHED THEN INSERT (
  JOB_NAME, DESCRIPTION, JOB_TYPE, JOB_LAYER,
  DBT_COMMAND, DBT_TARGET, DBT_WORKSPACE, DBT_PROJECT_FQN,
  IS_ENABLED, MIGRATED_FROM_WORKFLOW_ID, MIGRATED_FROM_WORKFLOW_STEP,
  CREATED_AT, CREATED_BY, UPDATED_AT, UPDATED_BY
) VALUES (
  S.JOB_NAME, S.DESCRIPTION, 'DBT', S.JOB_LAYER,
  S.DBT_COMMAND, S.DBT_TARGET, S.DBT_WORKSPACE, S.DBT_PROJECT_FQN,
  S.IS_ENABLED, S.SOURCE_WORKFLOW_ID, S.MODEL_SELECTOR,
  S.CREATED_AT, S.CREATED_BY, S.UPDATED_AT, S.UPDATED_BY
);

-- Assign each SQL job to its workflow.
MERGE INTO KUMO_TST.MONITOR_APP.WORKFLOW_JOB T
USING (
  SELECT W.WORKFLOW_ID, J.JOB_ID
  FROM KUMO_TST.MONITOR_APP.WORKFLOW W
  JOIN KUMO_TST.MONITOR_APP.JOB J
    ON J.MIGRATED_FROM_WORKFLOW_ID = W.MIGRATED_FROM_WORKFLOW_ID
   AND J.MIGRATED_FROM_WORKFLOW_STEP = 'SQL'
) S
ON T.WORKFLOW_ID = S.WORKFLOW_ID AND T.JOB_ID = S.JOB_ID
WHEN MATCHED THEN UPDATE SET
  T.PARENT_JOB_ID = NULL,
  T.JOB_SEQUENCE = 1,
  T.MIN_STATUS_LEVEL = 'SUCCESS',
  T.DEPENDENCY_TYPE = 'SEQUENCE',
  T.IS_ENABLED = TRUE,
  T.UPDATED_AT = CURRENT_TIMESTAMP(),
  T.UPDATED_BY = CURRENT_USER()
WHEN NOT MATCHED THEN INSERT (
  WORKFLOW_ID, JOB_ID, PARENT_JOB_ID, JOB_SEQUENCE,
  MIN_STATUS_LEVEL, DEPENDENCY_TYPE, IS_ENABLED
) VALUES (
  S.WORKFLOW_ID, S.JOB_ID, NULL, 1,
  'SUCCESS', 'SEQUENCE', TRUE
);

-- Assign DBT jobs in selector order and make every later model depend on the
-- preceding model succeeding.
MERGE INTO KUMO_TST.MONITOR_APP.WORKFLOW_JOB T
USING (
  WITH PARSED_MODELS AS (
    SELECT
      W.WORKFLOW_ID AS SOURCE_WORKFLOW_ID,
      F.INDEX::NUMBER AS JOB_SEQUENCE,
      TRIM(F.VALUE::VARCHAR) AS MODEL_SELECTOR
    FROM KUMO_ADMIN.WORKFLOW_MANAGER.WORKFLOWS W,
         LATERAL SPLIT_TO_TABLE(
           TRIM(SUBSTR(W.DBT_COMMAND, POSITION('-s' IN W.DBT_COMMAND) + 2)), ' '
         ) F
    WHERE UPPER(W.WORKFLOW_TYPE) = 'DBT'
      AND TRIM(F.VALUE::VARCHAR) <> ''
  ), RESOLVED_JOBS AS (
    SELECT
      TW.WORKFLOW_ID,
      J.JOB_ID,
      P.JOB_SEQUENCE
    FROM PARSED_MODELS P
    JOIN KUMO_TST.MONITOR_APP.WORKFLOW TW
      ON TW.MIGRATED_FROM_WORKFLOW_ID = P.SOURCE_WORKFLOW_ID
    JOIN KUMO_TST.MONITOR_APP.JOB J
      ON J.MIGRATED_FROM_WORKFLOW_ID = P.SOURCE_WORKFLOW_ID
     AND J.MIGRATED_FROM_WORKFLOW_STEP = P.MODEL_SELECTOR
  )
  SELECT
    WORKFLOW_ID,
    JOB_ID,
    LAG(JOB_ID) OVER (PARTITION BY WORKFLOW_ID ORDER BY JOB_SEQUENCE) AS PARENT_JOB_ID,
    JOB_SEQUENCE
  FROM RESOLVED_JOBS
) S
ON T.WORKFLOW_ID = S.WORKFLOW_ID AND T.JOB_ID = S.JOB_ID
WHEN MATCHED THEN UPDATE SET
  T.PARENT_JOB_ID = S.PARENT_JOB_ID,
  T.JOB_SEQUENCE = S.JOB_SEQUENCE,
  T.MIN_STATUS_LEVEL = 'SUCCESS',
  T.DEPENDENCY_TYPE = 'SEQUENCE',
  T.IS_ENABLED = TRUE,
  T.UPDATED_AT = CURRENT_TIMESTAMP(),
  T.UPDATED_BY = CURRENT_USER()
WHEN NOT MATCHED THEN INSERT (
  WORKFLOW_ID, JOB_ID, PARENT_JOB_ID, JOB_SEQUENCE,
  MIN_STATUS_LEVEL, DEPENDENCY_TYPE, IS_ENABLED
) VALUES (
  S.WORKFLOW_ID, S.JOB_ID, S.PARENT_JOB_ID, S.JOB_SEQUENCE,
  'SUCCESS', 'SEQUENCE', TRUE
);

-- Preserve today's ON_SUCCESS workflow chaining in the new relation table.
MERGE INTO KUMO_TST.MONITOR_APP.WORKFLOW_DEPENDENCY T
USING (
  SELECT
    PARENT_W.WORKFLOW_ID AS PARENT_WORKFLOW_ID,
    CHILD_W.WORKFLOW_ID AS CHILD_WORKFLOW_ID
  FROM (
    SELECT
      WT.WORKFLOW_ID AS SOURCE_PARENT_WORKFLOW_ID,
      F.VALUE::VARCHAR AS SOURCE_CHILD_WORKFLOW_ID
    FROM KUMO_ADMIN.WORKFLOW_MANAGER.WORKFLOW_TASKS WT,
         LATERAL FLATTEN(INPUT => WT.ON_SUCCESS) F
  ) R
  JOIN KUMO_TST.MONITOR_APP.WORKFLOW PARENT_W
    ON PARENT_W.MIGRATED_FROM_WORKFLOW_ID = R.SOURCE_PARENT_WORKFLOW_ID
  JOIN KUMO_TST.MONITOR_APP.WORKFLOW CHILD_W
    ON CHILD_W.MIGRATED_FROM_WORKFLOW_ID = R.SOURCE_CHILD_WORKFLOW_ID
) S
ON T.PARENT_WORKFLOW_ID = S.PARENT_WORKFLOW_ID
AND T.CHILD_WORKFLOW_ID = S.CHILD_WORKFLOW_ID
WHEN MATCHED THEN UPDATE SET
  T.MIN_STATUS_LEVEL = 'SUCCESS',
  T.DEPENDENCY_TYPE = 'TRIGGER',
  T.IS_ENABLED = TRUE,
  T.UPDATED_AT = CURRENT_TIMESTAMP(),
  T.UPDATED_BY = CURRENT_USER()
WHEN NOT MATCHED THEN INSERT (
  PARENT_WORKFLOW_ID, CHILD_WORKFLOW_ID,
  MIN_STATUS_LEVEL, DEPENDENCY_TYPE, IS_ENABLED
) VALUES (
  S.PARENT_WORKFLOW_ID, S.CHILD_WORKFLOW_ID,
  'SUCCESS', 'TRIGGER', TRUE
);
