-- First workflow migrated to the next-generation model.
-- This is additive: the existing KUMO_ADMIN workflow and its successors remain
-- unchanged and active during the parallel implementation track.

INSERT INTO KUMO_TST.MONITOR_APP.WORKFLOW (
  WORKFLOW_NAME,
  WORKFLOW_GROUP,
  DESCRIPTION,
  TASK_NAME,
  WAREHOUSE_NAME,
  SCHEDULE,
  SCHEDULE_TIMEZONE,
  IS_SCHEDULE_ENABLED,
  ALLOW_MANUAL_TRIGGER,
  ALLOW_EXTERNAL_TRIGGER,
  IS_ENABLED
)
SELECT
  'LOAD RAW DAILY',
  'GENERAL',
  'Loads the daily incremental RAW LIM delivery.',
  'WF_LOAD_RAW_DAILY',
  'KUMO_ELT_GEN_1',
  '0 6 * * 1-5',
  'UTC',
  TRUE,
  TRUE,
  TRUE,
  TRUE
WHERE NOT EXISTS (
  SELECT 1
  FROM KUMO_TST.MONITOR_APP.WORKFLOW
  WHERE WORKFLOW_NAME = 'LOAD RAW DAILY'
);

INSERT INTO KUMO_TST.MONITOR_APP.JOB (
  JOB_NAME,
  DESCRIPTION,
  JOB_TYPE,
  TASK_NAME,
  SQL_COMMAND,
  IS_ENABLED,
  MIGRATED_FROM_WORKFLOW_ID
)
SELECT
  'LOAD RAW DAILY',
  'Executes the existing RAW LIM incremental load procedure.',
  'SQL',
  'JOB_LOAD_RAW_DAILY',
  'CALL KUMO_TST.RAW_LIM.SP_LOAD_RAW_LIM_INCREMENTAL_PERSIST();',
  TRUE,
  '4a9e959a-63c2-4356-9dbf-2c56323493c3'
WHERE NOT EXISTS (
  SELECT 1
  FROM KUMO_TST.MONITOR_APP.JOB
  WHERE MIGRATED_FROM_WORKFLOW_ID = '4a9e959a-63c2-4356-9dbf-2c56323493c3'
);

INSERT INTO KUMO_TST.MONITOR_APP.WORKFLOW_JOB (
  WORKFLOW_ID,
  JOB_ID,
  JOB_SEQUENCE,
  IS_ENABLED
)
SELECT
  W.WORKFLOW_ID,
  J.JOB_ID,
  1,
  TRUE
FROM KUMO_TST.MONITOR_APP.WORKFLOW W
JOIN KUMO_TST.MONITOR_APP.JOB J
  ON J.MIGRATED_FROM_WORKFLOW_ID = '4a9e959a-63c2-4356-9dbf-2c56323493c3'
WHERE W.WORKFLOW_NAME = 'LOAD RAW DAILY'
  AND NOT EXISTS (
    SELECT 1
    FROM KUMO_TST.MONITOR_APP.WORKFLOW_JOB WJ
    WHERE WJ.WORKFLOW_ID = W.WORKFLOW_ID
      AND WJ.JOB_ID = J.JOB_ID
  );

