-- Correct the initial empty MONITOR_APP model so a job can be reused by more
-- than one workflow. Safe to apply only before JOB contains migrated rows.

ALTER TABLE KUMO_TST.MONITOR_APP.JOB
  DROP CONSTRAINT FK_MONITOR_JOB_WORKFLOW;

ALTER TABLE KUMO_TST.MONITOR_APP.JOB
  DROP CONSTRAINT UQ_MONITOR_JOB_NAME;

ALTER TABLE KUMO_TST.MONITOR_APP.JOB
  DROP CONSTRAINT UQ_MONITOR_JOB_SEQUENCE;

ALTER TABLE KUMO_TST.MONITOR_APP.JOB
  DROP COLUMN WORKFLOW_ID;

ALTER TABLE KUMO_TST.MONITOR_APP.JOB
  DROP COLUMN JOB_SEQUENCE;

ALTER TABLE KUMO_TST.MONITOR_APP.JOB
  ADD CONSTRAINT UQ_MONITOR_JOB_NAME UNIQUE (JOB_NAME);

ALTER TABLE KUMO_TST.MONITOR_APP.JOB SET
  COMMENT = 'Reusable executable units that can be assigned to one or more workflows';

CREATE TABLE IF NOT EXISTS KUMO_TST.MONITOR_APP.WORKFLOW_JOB (
  WORKFLOW_JOB_ID          VARCHAR(36)   NOT NULL DEFAULT UUID_STRING(),
  WORKFLOW_ID              VARCHAR(36)   NOT NULL,
  JOB_ID                   VARCHAR(36)   NOT NULL,
  JOB_SEQUENCE             NUMBER(9, 0)  NOT NULL,
  IS_ENABLED               BOOLEAN       NOT NULL DEFAULT TRUE,

  CREATED_AT               TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CREATED_BY               VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),
  UPDATED_AT               TIMESTAMP_NTZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  UPDATED_BY               VARCHAR(255)  NOT NULL DEFAULT CURRENT_USER(),

  CONSTRAINT PK_MONITOR_WORKFLOW_JOB PRIMARY KEY (WORKFLOW_JOB_ID),
  CONSTRAINT FK_MONITOR_WORKFLOW_JOB_WORKFLOW FOREIGN KEY (WORKFLOW_ID)
    REFERENCES KUMO_TST.MONITOR_APP.WORKFLOW (WORKFLOW_ID),
  CONSTRAINT FK_MONITOR_WORKFLOW_JOB_JOB FOREIGN KEY (JOB_ID)
    REFERENCES KUMO_TST.MONITOR_APP.JOB (JOB_ID),
  CONSTRAINT UQ_MONITOR_WORKFLOW_JOB UNIQUE (WORKFLOW_ID, JOB_ID),
  CONSTRAINT UQ_MONITOR_WORKFLOW_JOB_SEQUENCE UNIQUE (WORKFLOW_ID, JOB_SEQUENCE)
)
COMMENT = 'Ordered assignment of reusable jobs to workflows';

